#! /usr/bin/env python
# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(x):
    if x == 1:
        return 1
    elif x == 2:
        return 2
    else:
        return fib(x-1) + fib(x-2)

res = 0
number = 1

while fib(number)<4000000:
    if fib(number) % 2 == 0:
        res += fib(number)
    number += 1

print(res)
#./Problem2.py  6,84s user 0,01s system 99% cpu 6,862 total